###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "name": "sribabu Mandraju",
    "password": "12212123",
    "email": "sribabumandraju@gmail.com",
    "ID": "sribabu Mandraju"
}


###
POST http://localhost:3000/signin
Content-Type: application/json

{
    "email":"sribabu@gmail.com",
    "password": "12212123"
    
}

###
GET http://localhost:3000/allUsers
Content-Type: application/json


###
POST http://localhost:3000/msg/sendMessage/6669c771b3214de7f3632479
Content-Type: application/json

{
    "message": "Hi , I am fine?"
}


###
GET http://localhost:3000/msg/getMessages/6661a0fee8a3b33be43a484a/6669c771b3214de7f3632479
Content-Type: application/json
